### ISSUE TITLE
Java 17 Exception

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#119]
When building & starting Cottontail on Java 17, an exception is thrown at startup (see below). This does not seem to impact performance or functionality as far as i can tell.

```
java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.nio.ch.FileChannelImpl.setUninterruptible() accessible: module java.base does not "exports sun.nio.ch" to unnamed module @49b70bc7
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at jetbrains.exodus.io.FileDataWriter$Companion$setUninterruptibleMethod$1.invoke(FileDataWriter.kt:188) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.io.FileDataWriter$Companion$setUninterruptibleMethod$1.invoke(FileDataWriter.kt:185) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.util.UnsafeHolder.doPrivileged$lambda-0(UnsafeHolder.kt:30) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at jetbrains.exodus.util.UnsafeHolder.doPrivileged(UnsafeHolder.kt:29) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.io.FileDataWriter.<clinit>(FileDataWriter.kt:185) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.io.FileDataReaderWriterProvider.newFileDataWriter(FileDataReaderWriterProvider.kt:48) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.io.FileDataReaderWriterProvider.newReaderWriter(FileDataReaderWriterProvider.kt:30) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.log.LogConfig.createReaderWriter(LogConfig.java:359) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.log.LogConfig.getReader(LogConfig.java:125) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.log.Log.<init>(Log.kt:52) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:117) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:81) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:77) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments$newInstance$4.invoke(Environments.kt:46) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments$newInstance$4.invoke(Environments.kt:46) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments.prepare(Environments.kt:120) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at jetbrains.exodus.env.Environments.newInstance(Environments.kt:46) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at org.vitrivr.cottontail.dbms.catalogue.DefaultCatalogue.<init>(DefaultCatalogue.kt:80) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at org.vitrivr.cottontail.server.CottontailServer.<init>(CottontailServer.kt:24) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at org.vitrivr.cottontail.CottontailKt.embedded(Cottontail.kt:173) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at org.vitrivr.cottontail.CottontailKt.standalone(Cottontail.kt:121) ~[cottontaildb-dbms-0.15.0-all.jar:?]
	at org.vitrivr.cottontail.CottontailKt.main(Cottontail.kt:38) ~[cottontaildb-dbms-0.15.0-all.jar:?]
```

**Comment by ppanopticon** [comment]
This is a Xodus issue and unfortunately, there is nothing I can do about it. 

However, it will be fixed in a future version and indeed, it should not affect the functionality in any way. See [XD-856](https://youtrack.jetbrains.com/issue/XD-856)
