### ISSUE TITLE
Concurrent Inserts on the same table can cause a crash

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#15]
Unfortunately, i don't have a reproducible example. I _think_ what's causing the crash is two concurrent inserts which want to write to the same Volume (File, to be more specific) and then the second transaction wants to aquire the file lock, which causes an exception. (At least that's what i gather from the javadoc to `tryLock()`

Stacktrace:
```
ERROR CottonDMLService:84 - Insert failed because of a unknown error: null
java.nio.channels.OverlappingFileLockException
        at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
        at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
        at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
        at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
        at org.mapdb.CottontailDBVolume.acquireFileLock(CottontailDBVolume.kt:550)
        at org.mapdb.CottontailDBVolume.<init>(CottontailDBVolume.kt:69)
        at org.mapdb.CottontailDBVolume$CottontailDBVolumeFactory.factory(CottontailDBVolume.kt:57)
        at org.mapdb.CottontailDBVolume$CottontailDBVolumeFactory.makeVolume(CottontailDBVolume.kt:44)
        at org.mapdb.CottontailStoreWAL$realVolume$1.invoke(CottontailStoreWAL.kt:82)
```

**Comment by silvanheller** [comment]
This issue was fixed for VBS20
