### ISSUE TITLE
Preview in CLI / limit query causes java.lang.IllegalArgumentException when executed on empty entity

### ISSUE THREAD

**Issue by frankier** [vitrivr/cottontaildb#36]
Running `preview` in the CLI, which generates a limit query causes an `java.lang.IllegalArgumentException` when executed on an empty entity.

```
cottontaildb>count cineast cineast_segment
Counting elements of entity cineast.cineast_segment
2020-07-23 10:24:30 TRACE CottonDQLService:41 - Parsing & binding query aff5c7db-38fd-45b1-a07a-dfd4ae889e7c took 3ms.
2020-07-23 10:24:30 TRACE CottonDQLService:46 - Executing query aff5c7db-38fd-45b1-a07a-dfd4ae889e7c took 1ms.
2020-07-23 10:24:30 TRACE CottonDQLService:150 - Sending back 1 rows for position 0 of query aff5c7db-38fd-45b1-a07a-dfd4ae889e7c took 0ms.
2020-07-23 10:24:30 INFO  CottonDQLService:52 - Query aff5c7db-38fd-45b1-a07a-dfd4ae889e7c took 5ms.
data {
  key: "warren.cineast.cineast_segment.count()"
  value {
    longData: 0
  }
}
cottontaildb> preview cineast cineast_segment
Showing first 10 elements of entity cineast.cineast_segment
Previewing 10 elements of cineast_segment
2020-07-23 10:18:34 ERROR CottonDQLService:67 - Error while executing query query {
  from {
    entity {
      schema {
        name: "cineast"
      }
      name: "cineast_segment"
    }
  }
  projection {
    attributes {
      key: "*"
      value: ""
    }
  }
  limit: 10
}

java.lang.IllegalArgumentException: Start of a ranged entity scan cannot be greater than its end.
	at org.vitrivr.cottontail.database.queries.planning.nodes.basics.EntityScanNodeExpression$RangedEntityScanNodeExpression.<init>(EntityScanNodeExpression.kt:49)
	at org.vitrivr.cottontail.database.queries.planning.rules.LimitPushdownRule.apply(LimitPushdownRule.kt:22)
	at org.vitrivr.cottontail.database.queries.planning.CottontailQueryPlanner.generateCandidates(CottontailQueryPlanner.kt:53)
	at org.vitrivr.cottontail.database.queries.planning.CottontailQueryPlanner.optimize(CottontailQueryPlanner.kt:28)
	at org.vitrivr.cottontail.server.grpc.helper.GrpcQueryBinder.parseAndBindSimpleQuery(GrpcQueryBinder.kt:96)
	at org.vitrivr.cottontail.server.grpc.helper.GrpcQueryBinder.parseAndBind(GrpcQueryBinder.kt:60)
	at org.vitrivr.cottontail.server.grpc.services.CottonDQLService.query(CottonDQLService.kt:40)
	at org.vitrivr.cottontail.grpc.CottonDQLGrpc$MethodHandlers.invoke(CottonDQLGrpc.java:341)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:818)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Command execution failed: UNKNOWN: Query execution failed failed because of a unknown error: Start of a ranged entity scan cannot be greater than its end.
```

**Comment by frankier** [comment]
It seems to happen whenever there are less than the limit available

**Comment by ppanopticon** [comment]
Fixed!
