### ISSUE TITLE
Drop entity throws error and does not properly delete files

### ISSUE THREAD

**Issue by schoenja** [vitrivr/cottontaildb#54]
When attempting to drop an existing entity cottontail throws the following exception (on the dev branch).

Attempting to create a new entity with the same name afterwards does not work.
```
ERROR CottonDDLService:155 - Error while dropping entity 'warren.cottontail.tab4'
java.nio.file.NoSuchFileException: ./cottontaildb-data/schema_cottontail/entity_$tab4
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3824)
	at java.base/java.nio.file.Files.walk(Files.java:3878)
	at org.vitrivr.cottontail.database.schema.Schema.dropEntity(Schema.kt:206)
	at org.vitrivr.cottontail.server.grpc.services.CottonDDLService.dropEntity(CottonDDLService.kt:142)
	at org.vitrivr.cottontail.grpc.CottonDDLGrpc$MethodHandlers.invoke(CottonDDLGrpc.java:1075)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by ppanopticon** [comment]
Could you pull and try again? There was a typo in path.

**Comment by schoenja** [comment]
Seems to be working now, thank you :)
