### ISSUE TITLE
Optimizing entity with unique-hash index

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#58]
I don't have a clean example to reproduce this, but if you use the VBS2020-Dump (https://download-dbis.dmi.unibas.ch/vitrivr/cottontaildb-data.zip) and try to optimize the `cineast_tags` entity, the following error occurs (on windows, regardless of whether `forceUnmapMappedFiles` is set to true or false, you can also not delete the index):

```
2020-11-11 19:48:10 ERROR CottonDDLService:341 - Error while optimizing entity 'warren.cineast.cineast_tags'
org.mapdb.DBException$VolumeIOError
	at org.mapdb.volume.MappedFileVol.truncate(MappedFileVol.java:285)
	at org.mapdb.WriteAheadLog.destroyWalFiles(WriteAheadLog.java:791)
	at org.mapdb.StoreWAL.commit(StoreWAL.kt:643)
	at org.mapdb.DB.commit(DB.kt:435)
	at org.vitrivr.cottontail.database.index.hash.UniqueHashIndex$Tx.performCommit(UniqueHashIndex.kt:294)
	at org.vitrivr.cottontail.database.index.Index$Tx.commit(Index.kt:160)
	at org.vitrivr.cottontail.database.entity.Entity$Tx.commit(Entity.kt:365)
	at org.vitrivr.cottontail.database.general.TransactionKt.begin(Transaction.kt:42)
	at org.vitrivr.cottontail.database.entity.Entity.updateAllIndexes(Entity.kt:268)
	at org.vitrivr.cottontail.server.grpc.services.CottonDDLService.optimize(CottonDDLService.kt:326)
	at org.vitrivr.cottontail.grpc.CottonDDLGrpc$MethodHandlers.invoke(CottonDDLGrpc.java:1107)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Der Vorgang ist bei einer Datei mit einem ge�ffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
Caused by: java.io.IOException: Der Vorgang ist bei einer Datei mit einem ge�ffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar

	at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
	at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:430)
	at org.mapdb.volume.MappedFileVol.truncate(MappedFileVol.java:283)
	... 18 more

```

**Comment by ppanopticon** [comment]
I cannot reproduce this. Is this an issue that happens on Windows?

**Comment by ppanopticon** [comment]
Seems to be a Windows-related issue.

Apparently when you mmap the file, Windows prevents it from being truncated / deleted. See [Issue](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4715154).

There is several potential workarounds here:

1. We catch this exception and let it go silently. This is dangerous, because we might miss other (relevant) errors.
2. We refrain from using memory mapped files for indexes, which might incur some performance penalty.

Since we'll move away from memory mapped files with the new storage engine, I'd probably go for option 2. Any thoughts?

**Comment by silvanheller** [comment]
If option 2 is a quick fix, that's probably best.

**Comment by ppanopticon** [comment]
There is now a workaround for this on _dev_: Memory mapping can be switched of through a flag in _config.json_ Since MapDB files can be used in either mode, you can switch memory mapping off when importing data and switch it back on once you want to use it for querying.

Please mind:
- _dev_ uses a different ProtoBuf definition than master.
- Structure of config.json has changed so as to accommodate the new settings.
- There was an error with naming of indexes, which has been rectified on dev. You'll probably want to optimize all the relevant indexes.

**Comment by silvanheller** [comment]
Thanks!
